### ISSUE TITLE
Rewrite it in Rust.

### ISSUE THREAD

**Issue by WyvernAllow** [Legend2525/SexGPT#1]
Here are some reasons why Rust may be considered better than C++ in certain contexts:

Memory safety: Rust's ownership model and borrow checker ensure that memory safety errors such as null pointer dereferencing, dangling pointers, and buffer overflows are caught at compile-time, while in C++, they can only be detected at runtime or may go unnoticed, leading to security vulnerabilities and crashes.

Concurrency: Rust has built-in concurrency features, such as the actor-based model through the async and await keywords and the std::sync module, which allow developers to write thread-safe code without worrying about data races and deadlocks. In contrast, C++ requires manual management of threads and locks, which can be error-prone.

Syntax: Rust has a modern syntax that is easy to learn and read, with features such as pattern matching, algebraic data types, and macros that make it expressive and flexible. C++ has a more complex syntax, with a lot of legacy features and backward compatibility issues that can make it harder to write and maintain code.

Performance: Both Rust and C++ are fast languages, but Rust's ownership model and borrow checker allow for more efficient memory management and optimization, leading to potentially faster code. Additionally, Rust's compiler is known for producing optimized code with minimal runtime overhead.

To uninstall Visual C++, you can follow these steps:

Press the Windows key + R to open the Run dialog box.

Type "appwiz.cpl" in the Run dialog box and press Enter. This will open the Programs and Features window.

In the Programs and Features window, look for any entries related to Visual C++ Redistributable packages, such as "Microsoft Visual C++ 2015 Redistributable (x64)" or "Microsoft Visual C++ 2017 Redistributable (x86)".

Right-click on the entry of the Visual C++ Redistributable package that you want to uninstall and select "Uninstall" from the context menu.

Follow the on-screen prompts to complete the uninstallation process. You may be asked to restart your computer to complete the uninstallation.

Repeat this process for any other versions of the Visual C++ Redistributable packages that you want to uninstall.

**Comment by asdjawuq12** [comment]
Made an alt just to follow the development of uhh, this, but this seems like the right move tbf.

**Comment by Legend2525** [comment]
Listen here little man
Cpp is the superior language so there will be no need to rewrite it in rust(a language used by the weak and ***** members)
Here is why there will be no need for it to be rewritten in rust

Compile Time in Rust vs C++
Although, if we calculate the build times for C++ and Rust, they are almost the same, still it depends on how many templates we have implemented in the C++ project (the more templates, the more will compile time). But generally, C++ performs better when it comes to compiling time. Rust’s compiler is very user-friendly and offers many useful tools which provide error messages.

Pointers and Addresses
A pointer is an object that stores the memory address of another object. Most high-level and low-level languages have some or the other pointer functionality.

C++ provides the shared_ptr and the unique_ptr that can be used and treated like smart pointers. The standard library of Rust also provides many smart pointers. So both Rust and C++ use smart pointers which provide many advantages to them as a programming languages.

Object-Oriented Programming
As we already know, C++ is an object-oriented programming language, which is the biggest advantage of C++ over Rust, because Rust is not an object-oriented programming language. C++ provides many features as an Object-oriented language like Classes, objects, templates, [inheritance](https://www.scaler.com/topics/cpp/inheritance-in-cpp/), polymorphism, etc.

Concurrency
The concurrency features in Rust Programming's standard library are nearly similar to that of the C++ 11 version i.e. atomics, threads, condition variables, mutexes, etc. However, after the C++ 11 version, there is an addition of many new concurrency-related features in the C++ 14, C++ 17, and C++ 20 versions.

Compiler and Platform Support
Both C++ and Rust have multiple platform support like Windows 32 and 64-bit architectures, Mac, and Linux. But we have more compilers for C++ than that of Rust. As C++ is a widely used programming language, the compiler bugs and glitches are generally reported and fixed quickly, compared to Rust.

External Libraries
Both C++ and Rust offer excellent frameworks and libraries. In Rust, we have several frameworks that offer functional, secure, and robust code like Rocket, Nickel, Azul, etc. On the other hand, C++ contains its famous library known as STL or the Standard Template Library which is a collection of many useful classes and functions. It provides many containers which can be directly used as data structures, functions that provide different functionality and manipulation for these containers, generic strings, streams, and other language support.

Package-Management and Tooling
Rust has an official package manager known as Cargo which is similar to the package managers of Python and JavaScript. On the other hand, C++ also has some good package managers such as Conan. The Cargo is much easier to use than the Conan.

Support for Game Development
According to the current scenario, C++ is the most used language for game development and most of the games in the markets are built using C++. Also, the Unreal Engine is developed using C++, which is the most used framework for game development. Although Rust is also providing a platform for game development, it does have powerful frameworks as we have in C++. We can develop games in Rust, but it will take much more time compared to C++. So, to conclude we can say that C++ is a better choice for game development as compared to Rust.

Framework Support
Rust is famous for its framework support and has many useful frameworks such as Rocket (A web framework that provides better security, speed, and flexibility), Nickel (A framework that provides user-friendly information flow control systems), and Azul (A GUI framework used to develop desktop applications).

On the other hand, C++ has a rich library known as the STL (Standard Template Library) which contains many built-in functions.

Performance Levels
As both C++ and Rust are low-level languages, the applications build using both languages perform well in terms of latency and throughput. None of them rely on the garbage collector. The point to be kept in mind is that there is some specific optimization required in Rust code. C++ allows us to use safe controls such as smart pointers, but Rust goes with a binding syntax.

Community Support
Both languages have very large community support, C++ has the C++ ISO Committee while Rust has the Rust Foundation. The community of both languages is very active. But C++ has many more forums, open-source projects, and StackOverflow contributors. This is because C++ is a much older language compared to Rust.

Existing code base is more as compared with other languages in terms of Existing Products.
Compilation time is comparatively less.
Game Development is the area where this language performs outstanding.
C++ has multiple compilers i.e. GCC, Clang, Cfront, MinGW, LLVM, and many more.
C++ has its very vast STL i.e. Standard Template Library.
Some Myths Related to C++ and Rust
C++ arithmetic is safer than Rust.
The only advantage of Rust is object lifetime analysis.
C++ is faster than Rust.
Rust's safety isn't proved.
Rust won't help with C libraries.


But has a professional C++ user inspired by TensorFlow APi i can say that you clearly have tetanus and should see a doctor if you think your shit language is better than C++.. C++ is clearly the superior language

Jokes aside, both C++ and Rust are excellent programming languages with their own strengths and weaknesses. The choice between the two ultimately depends on the specific requirements of the project and the developer's personal preferences and expertise.

**Comment by Legend2525** [comment]
> Made an alt just to follow the development of uhh, this, but this seems like the right move tbf.
Rust or C++?

**Comment by asdjawuq12** [comment]
> > Made an alt just to follow the development of uhh, this, but this seems like the right move tbf.
> > Rust or C++?

Rust

**Comment by asdjawuq12** [comment]
What actually is this supposed to be exactly?

**Comment by Legend2525** [comment]
> > > Made an alt just to follow the development of uhh, this, but this seems like the right move tbf.
> > > Rust or C++?
> 
> Rust

 Rust would be good for AI due to its safer memory management but theres a dilemma that stems. Rust doesnt offer support for the "Best AI API" TensorFlow to which this "project" solely depends on.  Aswell as I have not learnt Rust due me not requiring it for what I do and its disadvantages compare to C++. :)

**Comment by asdjawuq12** [comment]
I get you, but 

> What actually is this supposed to be exactly?

**Comment by Legend2525** [comment]
> What actually is this supposed to be exactly?

Cough* uhhhh XD, well think of Chatgpt but with no restrictions, no codes of conduct, no rules and no terms and conditions.
Basically Chatgpt but you choose what ever you want answered without getting told, "As a AI chatbot I cannot provide sexual desires" or "No, I cannot be your virtual wife" Its basically Chatgpt but unlimited knowledge and infinitely more powerful.

Although, its still in working progress once its fully released it will not disappoint.

**Comment by Legend2525** [comment]
ik the name is **abit** much but its not finalized yet

**Comment by 1d2b** [comment]
Well now isnt this interesting.

**Comment by 1d2b** [comment]
> Listen here little man Cpp is the superior language so there will be no need to rewrite it in rust(a language used by the weak and ***** members) Here is why there will be no need for it to be rewritten in rust
> 
> Compile Time in Rust vs C++ Although, if we calculate the build times for C++ and Rust, they are almost the same, still it depends on how many templates we have implemented in the C++ project (the more templates, the more will compile time). But generally, C++ performs better when it comes to compiling time. Rust’s compiler is very user-friendly and offers many useful tools which provide error messages.
> 
> Pointers and Addresses A pointer is an object that stores the memory address of another object. Most high-level and low-level languages have some or the other pointer functionality.
> 
> C++ provides the shared_ptr and the unique_ptr that can be used and treated like smart pointers. The standard library of Rust also provides many smart pointers. So both Rust and C++ use smart pointers which provide many advantages to them as a programming languages.
> 
> Object-Oriented Programming As we already know, C++ is an object-oriented programming language, which is the biggest advantage of C++ over Rust, because Rust is not an object-oriented programming language. C++ provides many features as an Object-oriented language like Classes, objects, templates, [inheritance](https://www.scaler.com/topics/cpp/inheritance-in-cpp/), polymorphism, etc.
> 
> Concurrency The concurrency features in Rust Programming's standard library are nearly similar to that of the C++ 11 version i.e. atomics, threads, condition variables, mutexes, etc. However, after the C++ 11 version, there is an addition of many new concurrency-related features in the C++ 14, C++ 17, and C++ 20 versions.
> 
> Compiler and Platform Support Both C++ and Rust have multiple platform support like Windows 32 and 64-bit architectures, Mac, and Linux. But we have more compilers for C++ than that of Rust. As C++ is a widely used programming language, the compiler bugs and glitches are generally reported and fixed quickly, compared to Rust.
> 
> External Libraries Both C++ and Rust offer excellent frameworks and libraries. In Rust, we have several frameworks that offer functional, secure, and robust code like Rocket, Nickel, Azul, etc. On the other hand, C++ contains its famous library known as STL or the Standard Template Library which is a collection of many useful classes and functions. It provides many containers which can be directly used as data structures, functions that provide different functionality and manipulation for these containers, generic strings, streams, and other language support.
> 
> Package-Management and Tooling Rust has an official package manager known as Cargo which is similar to the package managers of Python and JavaScript. On the other hand, C++ also has some good package managers such as Conan. The Cargo is much easier to use than the Conan.
> 
> Support for Game Development According to the current scenario, C++ is the most used language for game development and most of the games in the markets are built using C++. Also, the Unreal Engine is developed using C++, which is the most used framework for game development. Although Rust is also providing a platform for game development, it does have powerful frameworks as we have in C++. We can develop games in Rust, but it will take much more time compared to C++. So, to conclude we can say that C++ is a better choice for game development as compared to Rust.
> 
> Framework Support Rust is famous for its framework support and has many useful frameworks such as Rocket (A web framework that provides better security, speed, and flexibility), Nickel (A framework that provides user-friendly information flow control systems), and Azul (A GUI framework used to develop desktop applications).
> 
> On the other hand, C++ has a rich library known as the STL (Standard Template Library) which contains many built-in functions.
> 
> Performance Levels As both C++ and Rust are low-level languages, the applications build using both languages perform well in terms of latency and throughput. None of them rely on the garbage collector. The point to be kept in mind is that there is some specific optimization required in Rust code. C++ allows us to use safe controls such as smart pointers, but Rust goes with a binding syntax.
> 
> Community Support Both languages have very large community support, C++ has the C++ ISO Committee while Rust has the Rust Foundation. The community of both languages is very active. But C++ has many more forums, open-source projects, and StackOverflow contributors. This is because C++ is a much older language compared to Rust.
> 
> Existing code base is more as compared with other languages in terms of Existing Products. Compilation time is comparatively less. Game Development is the area where this language performs outstanding. C++ has multiple compilers i.e. GCC, Clang, Cfront, MinGW, LLVM, and many more. C++ has its very vast STL i.e. Standard Template Library. Some Myths Related to C++ and Rust C++ arithmetic is safer than Rust. The only advantage of Rust is object lifetime analysis. C++ is faster than Rust. Rust's safety isn't proved. Rust won't help with C libraries.
> 
> But has a professional C++ user inspired by TensorFlow APi i can say that you clearly have tetanus and should see a doctor if you think your shit language is better than C++.. C++ is clearly the superior language
> 
> Jokes aside, both C++ and Rust are excellent programming languages with their own strengths and weaknesses. The choice between the two ultimately depends on the specific requirements of the project and the developer's personal preferences and expertise.

Well although this is correct, Rust will be alot more easy for this task.

**Comment by 1d2b** [comment]
> > What actually is this supposed to be exactly?
> 
> Cough* uhhhh XD, well think of Chatgpt but with no restrictions, no codes of conduct, no rules and no terms and conditions. Basically Chatgpt but you choose what ever you want answered without getting told, "As a AI chatbot I cannot provide sexual desires" or "No, I cannot be your virtual wife" Its basically Chatgpt but unlimited knowledge and infinitely more powerful.
> 
> Although, its still in working progress once its fully released it will not disappoint.

:)
